### ISSUE TITLE
Does it can work?

### ISSUE THREAD

**Issue by daimon99** [hustlzp/Flask-Boost#20]
env: windows/python2.7
error1: when install, exception throwed: tmpfile move exception. then I modify the source code, hard cord the args with "new project balabala"
error2: 
from application import create_app
from application.models import db
no application found.
...

**Comment by hustlzp** [comment]
我刚刚在 Mac OS 测了下，是可以的，之前尚未在 Windows 下测试。

你用的是 Flask-Boost 的哪个版本？

**Comment by hustlzp** [comment]
我刚才测试的版本是 0.6.0，直接通过 pip 安装后，命令行下运行 boost new project_name，是没问题的。

**Comment by daimon99** [comment]
我是windows10环境。一会我列下提示信息。

**Comment by daimon99** [comment]
# pip install flask-boost
```
Collecting flask-boost
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in c:\users\daimon\pycharmprojects\flaskboost\env\lib\site-packages (from flask-boost)
Installing collected packages: flask-boost
Successfully installed flask-boost-0.6.0
```
# boost new balabala
```
Start generating project files.
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Daimon\PycharmProjects\flaskboost\env\Scripts\boost.exe\__main__.py", line 9, in <module>
  File "c:\users\daimon\pycharmprojects\flaskboost\env\lib\site-packages\flask_boost\cli.py", line 292, in main
    generate_project(args)
  File "c:\users\daimon\pycharmprojects\flaskboost\env\lib\site-packages\flask_boost\cli.py", line 87, in generate_project
    _rewrite_and_copy(src_file, dst_file, project_name)
  File "c:\users\daimon\pycharmprojects\flaskboost\env\lib\site-packages\flask_boost\cli.py", line 321, in _rewrite_and_copy
    shutil.move(abs_path, dst_file)
  File "c:\python27\Lib\shutil.py", line 303, in move
    os.unlink(src)
WindowsError: [Error 32] : 'c:\\users\\daimon\\appdata\\local\\temp\\tmpqavpoa'
```

**Comment by hustlzp** [comment]
���������������� shutil.move �� windows ������������������������ windows ����������

�������� iPhone

> �� 2015��10��26��������11:23��daimon99 <notifications@github.com> ������
> 
> shutil.move

**Comment by hustlzp** [comment]
我去，乱码了。。。

应该是 shutil.move 不兼容 windows 的问题。

我晚上在 win7 下调试看看是否有这个问题。

**Comment by daimon99** [comment]
您在上班吗？好闲。。。回复真快，是应该高兴呢还是高兴呢？我在知春路，要不你来我这里调测吧:)

**Comment by hustlzp** [comment]
在北京创业，不过在东边，有点远。我有 Windows 机器，可以自测的。

发自我的 iPhone

**Comment by hustlzp** [comment]
发了个新版本，pip install -U flask-boost 试试。

**Comment by daimon99** [comment]
flask-boost版本从0.6.0升到0.6.2，但是好像代码没与这里的同步更新。我手工改下代码吧。

**Comment by daimon99** [comment]
# pip uninstall flask-boost
```
Uninstalling Flask-Boost-0.6.0:
  Successfully uninstalled Flask-Boost-0.6.0
```
# pip install flask-boost
```Collecting flask-boost
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in c:\users\daimon\pycharmprojects\flaskboost\env\lib\site-packages (from flask-boost)
Installing collected packages: flask-boost
Successfully installed flask-boost-0.6.0
```
# boost -v
Flask-Boost 0.6.0

**Comment by daimon99** [comment]
```
python manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from application import create_app
ImportError: No module named application
dir
2015/10/27  14:52             6,148 .DS_Store
2015/10/27  14:52               298 .gitignore
2015/10/27  14:52               314 bower.json
2015/10/27  14:52               793 fabfile.py
2015/10/27  14:52             1,401 fabfile.pyc
2015/10/27  14:52             2,432 gulpfile.js
2015/10/27  14:52             1,374 manage.py
2015/10/27  14:52             2,220 manage.pyc
2015/10/27  14:58    <DIR>          node_modules
2015/10/27  14:52               999 package.json
2015/10/27  14:52            10,009 pylintrc
2015/10/27  14:52                38 README.md
2015/10/27  14:52               350 requirements.txt
2015/10/27  14:52                56 wsgi.py
2015/10/27  14:52               259 wsgi.pyc
```

**Comment by hustlzp** [comment]
收到，我测测。

**Comment by hustlzp** [comment]
更新到0.7.0版本了，升级试试。

我这边（Windows 7）可以啦：

![img_5042](https://cloud.githubusercontent.com/assets/1180240/10754618/c6ec00e2-7cd3-11e5-9dd3-8a28e0a46754.JPG)

**Comment by daimon99** [comment]
OK now!
