### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword

### ISSUE THREAD

**Issue by sy264115809** [hustlzp/Flask-Boost#24]
After I run the command  `boost new boost-test`, I got this error:
```
Start generating project files.
New: ~/workspace/python/boost-test/
New: ~/workspace/python/boost-test/.gitignore
Traceback (most recent call last):
  File "/usr/local/bin/boost", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/flask_boost/cli.py", line 297, in main
    generate_project(args)
  File "/usr/local/lib/python2.7/site-packages/flask_boost/cli.py", line 87, in generate_project
    _rewrite_and_copy(src_file, dst_file, project_name)
  File "/usr/local/lib/python2.7/site-packages/flask_boost/cli.py", line 320, in _rewrite_and_copy
    with open(abs_path, 'w', encoding='utf-8') as new_file:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by hustlzp** [comment]
Thanks a lot!

I use `io.open` instead of `os.open` to support both Python 2.x and Python 3.x.

Try 0.7.5.

**Comment by sy264115809** [comment]
@hustlzp Thanks! It works.
